language: php
php:
  - 5.6
  - 7.0

before_script:
  - composer validate
  - composer update

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --repository="g/ntd/silverstripe-autotoc" --format=php-clover coverage.clover

